version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s  %(name)-30s %(levelname)-7s %(message)s'

handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        #filename: /var/log/myapp/myapp.log
        filename: logs/myapp.log

root:
    level: DEBUG
    handlers:
        - file